apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-working-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # ignored in Minikube
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
