# NGINX Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # Targets pods with label app: nginx
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 8080 # Container port
