namespace: nginx-namespace

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 80


serviceAccount:
  create: true
  name: ""

configMap:
  APP_MODE: "LOCAL"

fullnameOverride: ""
nameOverride: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []
