# Secret for MongoDB credentials (base64 encoded)
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU= # username
    mongo-root-password: cGFzc3dvcmQ= # password